name: Run Selenium Automation Daily at 6:00 AM IST

on:
  schedule:
    - cron: '30 0 * * *'  # 00:30 UTC = 6:00 AM IST
  workflow_dispatch:      # Allows manual trigger from Actions tab

jobs:
  run-jar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Google Chrome and ChromeDriver (auto-match)
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Verify Chrome and ChromeDriver
        run: |
          google-chrome --version
          chromedriver --version

      - name: Run Selenium Jar
        run: |
          echo "🚀 Starting CombineDownloadMergeTelegram.jar ..."
          java -jar CombineDownloadMergeTelegram.jar
