name: Run Selenium Automation Daily at 12:35 PM IST

on:
  schedule:
    - cron: '5 7 * * *'  # 7:05 AM UTC = 12:35 PM IST
  workflow_dispatch:      # Allows manual trigger from Actions tab

jobs:
  run-jar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Google Chrome
        run: |
          sudo apt update
          sudo apt install -y wget unzip curl
          wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          rm google-chrome-stable_current_amd64.deb
          google-chrome --version

      - name: Install ChromeDriver matching Chrome version
        run: |
          set -e
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          MAJOR_VERSION=$(echo $CHROME_VERSION | cut -d '.' -f1)
          echo "Detected Chrome version: $CHROME_VERSION"

          DRIVER_URL=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json" \
            | grep -A 3 "\"version\": \"$CHROME_VERSION\"" \
            | grep "chromedriver-linux64.zip" \
            | head -1 \
            | sed -E 's/.*https/https/' \
            | sed -E 's/\".*//')

          if [ -z "$DRIVER_URL" ]; then
            echo "⚠️ Exact match not found, trying latest available for major version $MAJOR_VERSION"
            DRIVER_URL=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json" \
              | grep -A 3 "\"version\": \"$MAJOR_VERSION" \
              | grep "chromedriver-linux64.zip" \
              | head -1 \
              | sed -E 's/.*https/https/' \
              | sed -E 's/\".*//')
          fi

          echo "Downloading ChromeDriver from: $DRIVER_URL"
          wget -qO /tmp/chromedriver.zip "$DRIVER_URL"
          unzip -o /tmp/chromedriver.zip -d /usr/local/bin/
          rm /tmp/chromedriver.zip
          chmod +x /usr/local/bin/chromedriver
          chromedriver --version

      - name: Run Selenium Jar
        run: |
          echo "🚀 Starting CombineDownloadMergeTelegram.jar ..."
          java -jar CombineDownloadMergeTelegram.jar
